name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # future-proof against Node 16 deprecation

      - name: Set up Node.js
        uses: actions/setup-node@v4 # future-proof against Node 16 deprecation
        with:
          node-version: '20'

      - name: Print Node.js version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          export NODE_ENV=production
          npm run build 2>&1 | tee build-log.txt

      - name: Capture build logs
        if: failure()
        run: cat build-log.txt

      - name: List build output
        run: ls -la .next

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          npm install -g gh-pages
          gh-pages -d out
        env:
          NODE_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
